services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: futurexdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:var/lib/postgresql/data
